export { default as Idea } from './Idea.jsx'
export { default as Service } from './Service.jsx'
export { default as Greeting } from './Greeting.jsx'
export { default as About } from './About.jsx'
export { default as Pop } from './CompanyPop.jsx'
export { default as PageBar } from './PageBar.jsx'