export {default as Top} from './main/top/Top.jsx'
export {default as Company} from './main/company/Company.jsx'
export {default as Contact} from './main/contact/Contact.jsx'
export {default as Recruit} from './main/recruit/Recruit.jsx'
export {default as Stock} from './main/stock/Stock.jsx'
